import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

import BottomNavigation from "@/components/Navigations/BottomNavigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <BottomNavigation children={children} />;
}
